knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"' # Notez les guillemets supplémentaires
        options:    []
    image:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"' # Notez les guillemets supplémentaires
        options:    []

