controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation


app_compte_edit:
    path: '/compte/edit/{id}'
    controller: 'App\Controller\CompteController::edit'
    methods: ['GET', 'POST']
