#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_interface:
    path: /userinterface
    controller: App\Controller\UserInterfaceController::index
admininterface:
    path: /admininterface
    controller: App\Controller\AdminInterfaceController::index
    # Add any additional configuration as needed
    # Example security.yaml snippet
# config/packages/security.yaml
# app/config/routes.yaml
# app/config/routes.yaml
images:
    path: /images
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: '%kernel.project_dir%/public/images'
        permanent: true
# config/routes.yaml
# config/routes.yaml
# config/routes.yaml

app_client_show:
    path: /client/{id}
    controller: App\Controller\ClientController::show
    methods: ['GET']
app_client_edit:
    path: '/client/{id}/edit'
    controller: 'App\Controller\ClientController::edit'
    methods: ['GET', 'POST']
# config/routes.yaml

# config/routes.yaml
decrement-solde:
    path: /decrement-solde
    controller: App\Controller\UserinterfaceController::decrementsolde
    methods: ['POST']

update-solde:
    path: /update-solde
    controller: App\Controller\UserinterfaceController::updatesolde
    methods: ['POST']

