# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twilio_account_sid: 'ACf8274d9e2bd87fe4670877052f812508'
    twilio_auth_token: 'b2e40d854a8115bd87fbc86fe33889bd'
    twilio_phone_number: '+19514358768'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Command\CalculInteretCommand:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    # config/services.yaml

    App\Service\SMSService:
        arguments:
            $accountSid: '%twilio_account_sid%'
            $authToken: '%twilio_auth_token%'
            $twilioPhoneNumber: '%twilio_phone_number%'


    App\Controller\virementAdmin:
        autowire: true
        autoconfigure: true
        public: false

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
